/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author HNIA
 */
public class MDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setTitle("Gestion des bourses");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuBourse = new javax.swing.JMenuItem();
        saveMenuEtudiant = new javax.swing.JMenuItem();
        jMenuAttribution = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuAjtBourse = new javax.swing.JMenuItem();
        copyMenuAttBourse = new javax.swing.JMenuItem();
        pasteMenuFiltrerType = new javax.swing.JMenuItem();
        deleteMenuRechEtud = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        openMenuBourse.setMnemonic('o');
        openMenuBourse.setText("Bourse");
        openMenuBourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuBourseActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuBourse);

        saveMenuEtudiant.setMnemonic('s');
        saveMenuEtudiant.setText("Etudiant");
        saveMenuEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuEtudiantActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuEtudiant);

        jMenuAttribution.setText("Attribution");
        jMenuAttribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAttributionActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuAttribution);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("statistique");

        cutMenuAjtBourse.setMnemonic('t');
        cutMenuAjtBourse.setText("Ajouter Bourse");
        editMenu.add(cutMenuAjtBourse);

        copyMenuAttBourse.setMnemonic('y');
        copyMenuAttBourse.setText("Attribuer Bourse");
        editMenu.add(copyMenuAttBourse);

        pasteMenuFiltrerType.setMnemonic('p');
        pasteMenuFiltrerType.setText("Filtrer par Type");
        editMenu.add(pasteMenuFiltrerType);

        deleteMenuRechEtud.setMnemonic('d');
        deleteMenuRechEtud.setText("Rechercher Etudiant");
        editMenu.add(deleteMenuRechEtud);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuBourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuBourseActionPerformed
        BourseForm bf = new BourseForm();
        desktopPane.add(bf);
        bf.setVisible(true);
    }//GEN-LAST:event_openMenuBourseActionPerformed

    private void saveMenuEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMenuEtudiantActionPerformed

    private void jMenuAttributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAttributionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAttributionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuAttBourse;
    private javax.swing.JMenuItem cutMenuAjtBourse;
    private javax.swing.JMenuItem deleteMenuRechEtud;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuAttribution;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuBourse;
    private javax.swing.JMenuItem pasteMenuFiltrerType;
    private javax.swing.JMenuItem saveMenuEtudiant;
    // End of variables declaration//GEN-END:variables

}
